packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  react: 19.1.0
  react-dom: 19.1.0
  next: 15.3.0
  typescript: 5.8.3
  '@types/node': ^22.15.3
  '@types/react': 19.1.8
  '@types/react-dom': 19.1.6
  eslint: ^9.29.0
  '@typescript-eslint/eslint-plugin': ^8.35.0
  '@typescript-eslint/parser': ^8.35.0
  typescript-eslint: ^8.33.0
  eslint-config-prettier: ^10.1.5
  eslint-plugin-prettier: ^5.5.0
  globals: ^16.2.0
  prettier: ^3.6.0
  turbo: ^2.5.4
  tsup: ^8.0.0
  vite: ^6.3.5
  '@vitejs/plugin-react': ^4.5.2
  storybook: ^8.6.14
  '@storybook/addon-essentials': ^8.6.14
  '@storybook/addon-interactions': ^8.6.14
  '@storybook/addon-links': ^8.6.14
  '@storybook/addon-onboarding': ^8.6.14
  '@storybook/blocks': ^8.6.14
  '@storybook/react': ^8.6.14
  '@storybook/react-vite': ^8.6.14
  '@storybook/test': ^8.6.14
  '@docusaurus/core': 3.8.1
  '@docusaurus/preset-classic': 3.8.1
  '@docusaurus/module-type-aliases': 3.8.1
  '@docusaurus/tsconfig': 3.8.1
  '@docusaurus/types': 3.8.1
  tailwindcss: ^3.4.17
  postcss: ^8.4.49
  autoprefixer: ^10.4.20
  type-fest: ^4.0.0
  clsx: ^2.1.1
  tailwind-merge: ^3.3.1
  '@mdx-js/react': ^3.0.0
  prism-react-renderer: ^2.3.0
  vitest: ^2.1.9
  '@testing-library/react': ^16.3.0
  '@testing-library/jest-dom': ^6.6.3
  '@testing-library/user-event': ^14.6.1
  jsdom: ^25.0.1
  axe-core: ^4.10.3
  '@axe-core/react': ^4.10.2
  lefthook: ^1.11.14
  oxlint: ^1.3.0
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@eslint/config-inspector': ^1.1.0
  '@turbo/gen': ^2.5.0
