packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  # Core frameworks
  react: '19.1.0'
  react-dom: '19.1.0'
  next: '15.3.0'

  # TypeScript
  typescript: '5.8.3'
  '@types/node': '^22.15.3'
  '@types/react': '19.1.8'
  '@types/react-dom': '19.1.6'

  # ESLint
  eslint: '^9.28.0'
  '@typescript-eslint/eslint-plugin': '^8.34.0'
  '@typescript-eslint/parser': '^8.34.0'
  typescript-eslint: '^8.33.0'
  eslint-config-prettier: '^10.1.1'
  eslint-plugin-prettier: '^5.4.1'
  globals: '^16.2.0'

  # Prettier
  prettier: '^3.5.3'

  # Build tools
  turbo: '^2.5.4'
  tsup: '^8.0.0'
  vite: '^6.3.5'
  '@vitejs/plugin-react': '^4.5.2'

  # Storybook
  storybook: '^8.6.14'
  '@storybook/addon-essentials': '^8.6.14'
  '@storybook/addon-interactions': '^8.6.14'
  '@storybook/addon-links': '^8.6.14'
  '@storybook/addon-onboarding': '^8.6.14'
  '@storybook/blocks': '^8.6.14'
  '@storybook/react': '^8.6.14'
  '@storybook/react-vite': '^8.6.14'
  '@storybook/test': '^8.6.14'

  # Docusaurus
  '@docusaurus/core': '3.8.1'
  '@docusaurus/preset-classic': '3.8.1'
  '@docusaurus/module-type-aliases': '3.8.1'
  '@docusaurus/tsconfig': '3.8.1'
  '@docusaurus/types': '3.8.1'

  # Styling
  tailwindcss: '^3.4.17'
  postcss: '^8.4.49'
  autoprefixer: '^10.4.20'

  # Utilities
  type-fest: '^4.0.0'
  clsx: '^2.0.0'
  tailwind-merge: '^3.3.1'
  '@mdx-js/react': '^3.0.0'
  prism-react-renderer: '^2.3.0'

  # Testing
  vitest: '^2.1.2'
  '@testing-library/react': '^16.1.2'
  '@testing-library/jest-dom': '^6.6.3'
  '@testing-library/user-event': '^14.5.2'
  jsdom: '^25.0.1'

  # Dev tools
  lefthook: '^1.11.13'
  oxlint: '^1.1.0'
  '@commitlint/cli': '^19.8.1'
  '@commitlint/config-conventional': '^19.8.1'
  '@eslint/config-inspector': '^1.0.0'
  '@turbo/gen': '^2.5.0'
