project:
  label: プロジェクト
  permalink: /project
  description: プロジェクト全般に関する記事

requirements:
  label: 要件定義
  permalink: /requirements
  description: プロジェクトの要件定義や仕様に関する記事

blog:
  label: ブログ
  permalink: /blog
  description: ブログ開発や設計に関する記事

planning:
  label: 計画
  permalink: /planning
  description: プロジェクト計画や設計に関する記事

packages:
  label: パッケージ
  permalink: /packages
  description: モノレポパッケージの開発や設定に関する記事

utils:
  label: ユーティリティ
  permalink: /utils
  description: 共有ユーティリティパッケージに関する記事

monorepo:
  label: モノレポ
  permalink: /monorepo
  description: モノレポ構成や管理に関する記事

typescript:
  label: TypeScript
  permalink: /typescript
  description: TypeScript設定や開発に関する記事

setup:
  label: セットアップ
  permalink: /setup
  description: 環境構築や初期設定に関する記事

pnpm:
  label: pnpm
  permalink: /pnpm
  description: pnpmパッケージマネージャーに関する記事

turborepo:
  label: TurboRepo
  permalink: /turborepo
  description: TurboRepoの設定や使用方法に関する記事

tasks:
  label: タスク
  permalink: /tasks
  description: タスク管理や自動化に関する記事

dependencies:
  label: 依存関係
  permalink: /dependencies
  description: パッケージ間の依存関係に関する記事

troubleshooting:
  label: トラブルシューティング
  permalink: /troubleshooting
  description: 問題解決や修正方法に関する記事

dependency-management:
  label: 依存関係管理
  permalink: /dependency-management
  description: パッケージの依存関係管理に関する記事

renovate:
  label: Renovate
  permalink: /renovate
  description: Renovateを使用した自動化に関する記事

automation:
  label: 自動化
  permalink: /automation
  description: 開発プロセスの自動化に関する記事

react:
  label: React
  permalink: /react
  description: React開発に関する記事

docusaurus:
  label: Docusaurus
  permalink: /docusaurus
  description: Docusaurusフレームワークに関する記事

bug:
  label: バグ
  permalink: /bug
  description: バグや不具合に関する記事

storybook:
  label: Storybook
  permalink: /storybook
  description: Storybookに関する記事

migration:
  label: マイグレーション
  permalink: /migration
  description: バージョンアップやマイグレーションに関する記事

frontend-tooling:
  label: フロントエンドツール
  permalink: /frontend-tooling
  description: フロントエンド開発ツールに関する記事
